version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: campus_health
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/campus_health
      - REDIS_URL=redis://redis:6379
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:4000
      - VITE_SOCKET_SERVER_URL=http://localhost:4000
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
